### ISSUE TITLE
Some values in the spatial data do not have an associated state in the network node.

### ISSUE THREAD

**Issue by CamillaNegri** [dariomasante/bnspatial#13]
Hi Dario,

I am using bnspatial for the first time with a spatial layer with continuous values. I get this message:

`Some values in the spatial data do not have an associated state in the network node. The following values will be treated as NA: 8.00602000427246, 8.05875575421593, 8.09402885559474, 8.15999984741211, 8.16289984703064, 8.17201171194823, 8.17608467789083, 8.2011417617926, 8.25, 8.25238804870777, 8.27000045776367, 8.28477827755444, 8.28637875609543, 8.28999996185303, 8.30963083413931, 8.31822148906794, 8.31999969482422, 8.32239982604981, 8.32323140498621, 8.32366436004639no non-missing arguments to min; returning Infno non-missing arguments to max; returning -Inf`

I'm not a 100% sure what is happening, but I have checked that the names of layers, nodes and states correspond. I am also using -Inf and Inf as lower and upper boundary. The values stated here would be in the state defined as -Inf, 20.
The code runs but I believe the results are not credible. Do you have insight on what is going on and how I could correct this?

Many thanks and best wishes,
Camilla

**Comment by dariomasante** [comment]
It's hard to figure out with no code or at least the lookup table. It appears as if it's taking continuous values as discrete values. Check your lookup list contains the right boundaries, so if you have states A and B to associate to raster values, then you must have values like -Inf, 20, Inf  . If that is not the case try replace -Inf and Inf with some values. Otherwise I cant help without code to reproduce the error.

**Comment by CamillaNegri** [comment]
Dear Dario, 
Thanks for your patience. Unfortunately I cannot share my material at the moment, but I think I found the mistake: I forgot that with the function `linkMultiple`, the spatial data needs to be in the same order as it is in the lookup (and it wasn't).

Again many thanks for your patience and help!
