### ISSUE TITLE
lookup states

### ISSUE THREAD

**Issue by e3cleary** [dariomasante/bnspatial#5]
Hi,
Is there any way to avoid defining states for the 'lookup' argument in bnspatial.
The data on which my bn model is trained contains vector and spatial data, all continuous variables.  To generate a network using bnlearn package, I first discretise the variables in R. I end up with a dataset with classBoundaries defined, but no defined states. I've tried assigning labels to levels within the variables after they've been discretised, but have gotten the following error - " evi_med " missing from network node : " EVI_Jul_recode_100_10km.tif "Names of states provided do not match the node states from the network.

Thanks,

Eimear

**Comment by dariomasante** [comment]
Hi,
it's difficult to provide a solution without a reproducible example or at least a snapshot of the data structure. 'lookup' argument is mandatory because otherwise it's impossible to establish correspondence between a raster and its node, as well as between the node states and the values in the raster. I avoided default values or names matching on purpose because it lacks of generality and almost certainly leads to wrong attributions.  

My suggestion is to build the object required by 'lookup' argument using the function ?setClasses. 
The nodes and their states in a grain object should have a name and those names must be provided to setClasses, plus the corresponding class boundaries in the spatial data (or values for categorical raster). This should guarantee consistence in naming. Must avoid spaces in names too.

Note that if you're using the wrapping function 'bnspatial', the list of  rasters provided to its argument 'spatialData' must be in the right order as their correspondent nodes in the lookup. E.g.  if your lookup list has first $B, then $A, you should specify spatialData=c('b.tif','a.tif').

**Comment by e3cleary** [comment]
Hi

Thanks for your reply. I've tried to define the nodes, states & class
boundaries for the lookup argument as both a text file and using the
SetClasses function. I ran a 'querygrain' on the grain object to examine
the states and names. I can't seem to specify the states correctly however,
and I'm at a loss as to how to proceed.
For context, the original dataset contains both vector and spatial data, as
either continuous or categorical variables. (See PDF attached - 'original
data'). Four of the variables are spatial/raster data (variables in 'BN
classes txt file' section of PDF).

I discretised the data to train the bn (PDF file - Data discretised for BN
in R), and these discretised values should represent the 'states' in the
nodes.

I can't seem to appropriately name the states however and keep getting
error messages in R.

Any insight you can give is most appreciated.

Kind regards.

**Comment by dariomasante** [comment]
Hi, I can't see any pdf attached. I think you have to reply from github comment box to share attachments, not by email. Cheers

**Comment by e3cleary** [comment]
Hi,

Thanks. Will send on now. Thanks for your help!

**Comment by e3cleary** [comment]
[bnspatial.pdf](https://github.com/dariomasante/bnspatial/files/1138099/bnspatial.pdf)

**Comment by dariomasante** [comment]
Wow, let's try...
- It looks like you have used native R function 'cut' to discretize your variables: it's ok, but if you provide nicer levels/labels names than the defaults you may find mistakes quicker. For instance I see sometimes square brackets only(the text file), sometimes no brackets at all (last snapshot), sometimes a mix (the grain object). 
- This is also root of the error in the first instance: when using the text file as input for the 'lookup' argument, you must avoid strings containing commas. Comma is used in function 'importClasses' to split the caracter vectors into state names. Indeed any other character is fine. Commas are allowed if you provide the list directly, but again, put some sensible names in your BN!
- When using the 'bnspatial' wrapper, you may not need to discretize spatial data beforehand, since the 'lookup' argument you provide contains the info to do that and will do that internally for you. Of course all labels must match with those in the BN (see above).
- If you need to do that anyway (e.g. to train the BN), in bnspatial there is a generic function to discretize continuous data, which provides a list with some additional items useful for the steps afterwards: see ?dataDiscretize and examples therein. 
- A final note concerning non-spatial data (may not apply to you, but anyway), if it's known and genuinely non-spatial in its nature, then must have a single value across the whole geographical area and therefore be fixed as evidence; otherwise it is implicitly spatial and it should be rasterised beforehand and treated as spatial data. Also if you have only a few points, say, it does not matter, as missing values elsewhere are handled well in BN.
