### ISSUE TITLE
decision and non-spatial nodes 

### ISSUE THREAD

**Issue by danivapp** [dariomasante/bnspatial#6]
I have constructed a BBN in GeNIe. It contains a combination of spatially explicit nodes (rasters) as well as non-spatial information, such as expert opinion or decision nodes. Is it posible to conduct the analysis using `bnspatial`?

I tried combining non-spatial information and spatial information on a smaller network of only 4 nodes: 
![hazard](https://user-images.githubusercontent.com/26418850/39046889-22071780-4498-11e8-855b-a2cf554613af.PNG). 
I imported the network (`hazard_subnetwork`), corresponding discretized raster files: `ekin.raster.clases`, `reachPr.raster.clases` and lookup .txt file. When running the query, I get an error: 

```
# loading data 
  spatialData <- c(ekin.raster.clases, reachPr.raster.clases)
  lookup <- "C:/...path.../lookup_hazard.txt"
  target <- 'hazard'
  
  bn <- bnspatial(hazard_subnetwork, target, spatialData, lookup)

Read 6 items

"Intensity" points to:
 ->   

With states:
low    moderate    high

Represented by integer values:
1 <-> 2 <-> 3
----------------------------------

"probability" points to:
 ->   

With states:
low    moderate    high

Represented by integer values:
1 <-> 2 <-> 3
----------------------------------
Lookup table to interpret "hazard" values:
    hazard cell_ID
1      low       1
2 moderate       2
3     high       3
```
**Problem**:

1.  Node `probability `and `Intensity ` point to nowhere, despite that according to the model they should be pointing to the target variable `hazard`. (This issue is probably related the the following point). 

2. I have not specified node `rock mass scenario` in any way. It has 4 states: `none`, `30yrs`, `100yers`, `300yrs ` and according to the state, different `ekin.raster.clases`, `reachPr.raster.clases` should be retrieved. Can this be modeled in `bnspatial`?

**Comment by dariomasante** [comment]
What error do you get? It looks like the problem is in your lookup table, which you don't provide. 
Do your two rasters relate to "intensity" and "probability" nodes? If so your lookup table should look like:
```
intensity 
low,moderate,high 
[raster value associated with low], [raster value associated with moderate],[raster value associated with high] 
```
...and so on, see `?setClasses` and the vignette at https://cran.r-project.org/web/packages/bnspatial/vignettes/bnspatial.html

Also, you're misunderstanding the message: "points to" does not refer to any network node, the message is there for the user to check whether the node has been related to the right raster, it refers to the source of the spatial data; it should be read as "reads from spatial data source: <yourRaster>". 

Finally, if you have decision nodes, just make a normal chance nodes, then treat like evidence the state you wish to use as decision (e.g. Intensity = 'moderate')
